[versions]
androidGradlePlugin = "8.7.3"
kotlin = "2.1.20"
kotlinxSerializationJson = "1.8.0"

livedigitalSdk = "1.5.0"

appcompat = "1.7.0"
material = "1.12.0"
recyclerview = "1.4.0"

retrofit = "2.11.0"
loggingInterceptor = "4.12.0"
koin = "4.0.2"

permissionChecker = "0.1"

[libraries]
livedigital-sdk = { group = "com.github.vlprojects", name = "livedigital-android-sdk", version.ref = "livedigitalSdk" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

sequenia-permissionChecker = { group = "com.github.sequenia", name = "Permission-Checker", version.ref = "permissionChecker" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }